"""add fsm table

Revision ID: e9da1f90dd40
Revises: b4d4a8a1f84c
Create Date: 2023-09-28 14:17:28.117635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9da1f90dd40'
down_revision: Union[str, None] = 'b4d4a8a1f84c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fsm_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), server_default='{}', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_ids', 'fsm_data', ['bot_id', 'chat_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index_ids', table_name='fsm_data')
    op.drop_table('fsm_data')
    # ### end Alembic commands ###
