"""added text_answer field to user_attempt table

Revision ID: d3e12c0bd319
Revises: 27b03a1b5a92
Create Date: 2023-09-11 23:43:42.453471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e12c0bd319'
down_revision: Union[str, None] = '27b03a1b5a92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_question_attempts', sa.Column('text_answer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_question_attempts', 'text_answer')
    # ### end Alembic commands ###
